name: result
description: A functional programming Result type for Dart and Flutter with pattern matching support.
version: 1.2.0
repository: https://github.com/p424p424/flutter_pkg_result

publish_to: none

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
